### ISSUE TITLE
Git Action on delete does not consider filters, does not work

### ISSUE THREAD

**Issue by gboege** [FIWARE-Ops/i4trust-demonstrator#1]
https://github.com/FIWARE-Ops/i4trust-demonstrator/blob/87a92bef082098a444c44e6ce1210ad414184d6a/.github/workflows/cleanup.yaml#L6

Described here:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#delete

In Contrast to here in push:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

Workaround (not perfect) here:
https://github.com/orgs/community/discussions/10589#discussioncomment-5260448

**Comment by dwendland** [comment]
Do you provide a PR?

**Comment by gboege** [comment]
I have implemented a work-around in KIMarktplatz. That uses a skip workflow mechanism, but leaves ugly traces in the list of history workflow. I will explain to you offline to align or not.

**Comment by gboege** [comment]
As we discussed in Vienna with Stefan, the issue of deployment should not be made more complicated. We leave as it is. Will close the case
